# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPIForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrs_1_t0', models.CharField(blank=True, max_length=2, null=True, verbose_name='Dolore peggiore a T0')),
                ('nrs_1_t1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Dolore peggiore a T1')),
                ('nrs_2_t0', models.CharField(blank=True, max_length=2, null=True, verbose_name='Dolore più lieve a T0')),
                ('nrs_2_t1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Dolore più lieve a T1')),
                ('nrs_3_t0', models.CharField(blank=True, max_length=2, null=True, verbose_name='Dolore medio a T0')),
                ('nrs_3_t1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Dolore medio a T1')),
                ('nrs_4_t0', models.CharField(blank=True, max_length=2, null=True, verbose_name='Dolore al momento a T0')),
                ('nrs_4_t1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Dolore al momento a T1')),
                ('sollievo_indotto_t0', models.CharField(blank=True, max_length=4, null=True, verbose_name='% Sollievo indotto a T0')),
                ('sollievo_indotto_t1', models.CharField(blank=True, max_length=4, null=True, verbose_name='% Sollievo indotto a T1')),
                ('attivita_generale_t0', models.CharField(blank=True, max_length=2, null=True, verbose_name='Attività in generale a T0')),
                ('attivita_generale_t1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Attività in generale a T1')),
                ('umore_t0', models.CharField(blank=True, max_length=2, null=True, verbose_name='Umore a T0')),
                ('umore_t1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Umore a T1')),
                ('camminare_t0', models.CharField(blank=True, max_length=2, null=True, verbose_name='Capacità di camminare a T0')),
                ('camminare_t1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Capacità di camminare a T1')),
                ('lavoro_t0', models.CharField(blank=True, max_length=2, null=True, verbose_name='Lavoro a T0')),
                ('lavoro_t1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Lavoro a T1')),
                ('relazioni_t0', models.CharField(blank=True, max_length=2, null=True, verbose_name='Relazioni a T0')),
                ('relazioni_t1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Relazioni a T1')),
                ('sonno_t0', models.CharField(blank=True, max_length=2, null=True, verbose_name='Sonno a T0')),
                ('sonno_t1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Sonno a T1')),
                ('gusto_vivere_t0', models.CharField(blank=True, max_length=2, null=True, verbose_name='Gusto di vivere a T0')),
                ('gusto_vivere_t1', models.CharField(blank=True, max_length=2, null=True, verbose_name='Gusto di vivere a T1')),
                ('altro', models.TextField(blank=True, null=True, verbose_name='Altro')),
            ],
            options={
                'verbose_name_plural': 'BPI',
                'verbose_name': 'BPI',
            },
        ),
        migrations.CreateModel(
            name='EventiAvversi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tachicardia', models.BooleanField(default=False, verbose_name='Tachicardia')),
                ('ipotensione_post', models.BooleanField(default=False, verbose_name='Ipotensione posturale')),
                ('cefalea', models.BooleanField(default=False, verbose_name='Cefalea')),
                ('iper_congiuntivale', models.BooleanField(default=False, verbose_name='Iperemia congiuntivale')),
                ('tosse', models.BooleanField(default=False, verbose_name='Irritazione bronchiale, tosse')),
                ('astenia', models.BooleanField(default=False, verbose_name='Astenia')),
                ('disforia', models.BooleanField(default=False, verbose_name='Disforia')),
                ('crisi_ansia', models.BooleanField(default=False, verbose_name='Crisi di ansia e panico')),
                ('concentrazione', models.BooleanField(default=False, verbose_name='Difficoltà di concentrazione')),
                ('fauci', models.BooleanField(default=False, verbose_name='Secchezza delle fauci')),
                ('sonnolenza', models.BooleanField(default=False, verbose_name='Sonnolenza, sedazione')),
                ('confusione', models.BooleanField(default=False, verbose_name='Stato confusionale')),
                ('amotivazione', models.BooleanField(default=False, verbose_name='Sindrome amotivazionale')),
                ('delirio', models.BooleanField(default=False, verbose_name='Crisi psicotica acuta / delirio')),
            ],
            options={
                'verbose_name_plural': 'Eventi Avversi',
                'verbose_name': 'Eventi Avversi',
            },
        ),
        migrations.CreateModel(
            name='ModalitaDecotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_acqua', models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantità acqua (ml)')),
                ('sostanza_grassa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sostanza grassa utilizzata (butto,latte, panna) e quantità (ml)')),
                ('tempo_impiegato', models.CharField(blank=True, max_length=5, null=True, verbose_name='Tempo intercorso tra la preparazione del decotto (min)')),
                ('tempo_assunzione', models.CharField(blank=True, max_length=10, null=True, verbose_name="Tempo intercorso tra la preparazione e l'assunzione (min)")),
            ],
            options={
                'verbose_name_plural': 'Modalità decotto',
                'verbose_name': 'Modalità decotto',
            },
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_paziente', models.CharField(blank=True, max_length=10, null=True, verbose_name='N° Paziente')),
                ('num_cartella', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Cartella')),
                ('nome', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nome')),
                ('cognome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cognome')),
                ('sesso', models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1, null=True, verbose_name='Sesso')),
                ('data_nascita', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('eta', models.CharField(blank=True, max_length=2, null=True, verbose_name='Età')),
                ('lavoro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavoro')),
                ('titolo_studio', models.CharField(blank=True, choices=[('0', 'Elementari'), ('1', 'Licenza Media Inferiore'), ('2', 'Licenza Media Superiore'), ('3', 'Laurea')], max_length=1, null=True, verbose_name='Titolo di studio')),
                ('patologia', models.CharField(blank=True, choices=[('0', 'Dolore neuropatico cronico'), ('1', 'Patologia oncologica'), ('2', 'Spasticità dolorosa'), ('3', 'Sindrome fibromialgica'), ('4', 'Cefalea')], max_length=1, null=True, verbose_name='Patologia')),
                ('descrizione_patologica', models.TextField(blank=True, null=True, verbose_name='Descrizione patologia')),
                ('eta_insorgenza', models.CharField(blank=True, max_length=2, null=True, verbose_name="Età anagrafica all'insorgenza della patologia dolorosa")),
                ('altre_patologie', models.TextField(blank=True, null=True, verbose_name='Altre patologie')),
                ('trattamenti', models.TextField(blank=True, null=True, verbose_name='Trattamenti farmacologici in corso')),
                ('posologia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Posologia (mg/die)')),
                ('num_somministrazioni', models.CharField(blank=True, max_length=300, null=True, verbose_name='Numero di somministrazioni/die')),
                ('data_trattamento', models.DateField(blank=True, null=True, verbose_name='Data di inizio trattamento')),
                ('modalita_somministrazione', models.CharField(blank=True, choices=[('0', 'Orale - Cartine'), ('1', 'Orale - Capsule apribili'), ('2', 'Orale - Olio'), ('3', 'Inalazione')], max_length=1, null=True, verbose_name='Modalità di somministrazione')),
                ('utilizzo_cannabis', models.NullBooleanField(verbose_name='Utilizzo cannabis prescritta per terapia orale anche     \t\tcon altre modalità di somministrazione (es. per smoking)')),
                ('tempo_prelievo', models.CharField(blank=True, max_length=100, null=True, verbose_name="Tempo trascorso tra l'assunzione della cannabis e il \t\t\tprelievo ematico (minuti)")),
                ('cannabis_ricreazionale', models.NullBooleanField(verbose_name='Attuale utilizzo di cannabis ricreazionale')),
                ('pregresso_utilizzo_ricreazionale', models.NullBooleanField(verbose_name='Pregresso utilizzo di cannabis ricreazonale')),
                ('uso_stupefacenti', models.NullBooleanField(verbose_name='Uso di sostanze stupefacenti')),
            ],
            options={
                'verbose_name_plural': 'Pazienti',
                'verbose_name': 'Paziente',
            },
        ),
        migrations.AddField(
            model_name='modalitadecotto',
            name='paziente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decotto_paziente', to='pazienti.Paziente', verbose_name='Paziente'),
        ),
        migrations.AddField(
            model_name='eventiavversi',
            name='paziente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi_paziente', to='pazienti.Paziente', verbose_name='Paziente'),
        ),
        migrations.AddField(
            model_name='bpiform',
            name='paziente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpi_paziente', to='pazienti.Paziente', verbose_name='Paziente'),
        ),
    ]
