# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_paziente', models.CharField(blank=True, max_length=10, null=True, verbose_name='N° Paziente')),
                ('num_cartella', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Cartella')),
                ('nome', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sesso')),
                ('cognome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sesso')),
                ('sesso', models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1, null=True, verbose_name='Sesso')),
                ('data_nascita', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('eta', models.CharField(blank=True, max_length=2, null=True, verbose_name='Età')),
                ('lavoro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavoro')),
                ('titolo_studio', models.CharField(blank=True, choices=[('0', 'Elementari'), ('1', 'Licenza Media Inferiore'), ('2', 'Licenza Media Superiore'), ('3', 'Laurea')], max_length=1, null=True, verbose_name='Titolo di studio')),
                ('patologia', models.CharField(blank=True, choices=[('0', 'Dolore neuropatico cronico'), ('1', 'Patologia oncologica'), ('2', 'Spasticità dolorosa'), ('3', 'Sindrome fibromialgica'), ('4', 'Cefalea')], max_length=1, null=True, verbose_name='Patologia')),
                ('descrizione_patologica', models.TextField(blank=True, null=True, verbose_name='Descrizione patologica')),
                ('eta_insorgenza', models.CharField(blank=True, max_length=2, null=True, verbose_name="Età anagrafica all'insorgenza della patologia dolorosa")),
                ('altre_patologie', models.TextField(blank=True, null=True, verbose_name='Altre patologie')),
                ('trattamenti', models.TextField(blank=True, null=True, verbose_name='Trattamenti farmacologici in corso')),
            ],
        ),
    ]
