# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pazienti', '0002_auto_20170225_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventiavversi',
            name='altro',
            field=models.TextField(blank=True, null=True, verbose_name='Altro'),
        ),
        migrations.AddField(
            model_name='paziente',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
