# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pazienti', '0004_auto_20170301_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='paziente',
            name='conc_11_oh_thc_dbs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Concentrazione 11-OH-THC - DBS'),
        ),
        migrations.AddField(
            model_name='paziente',
            name='conc_11_oh_thc_sangue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Concentrazione 11-OH-THC - Sangue intero'),
        ),
        migrations.AddField(
            model_name='paziente',
            name='conc_cbd_dbs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Concentrazione CBD - DBS'),
        ),
        migrations.AddField(
            model_name='paziente',
            name='conc_cbd_sangue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Concentrazione CBD - Sangue intero'),
        ),
        migrations.AddField(
            model_name='paziente',
            name='conc_thc_dbs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Concentrazione THC - DBS'),
        ),
        migrations.AddField(
            model_name='paziente',
            name='conc_thc_sangue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Concentrazione THC - Sangue intero'),
        ),
    ]
