# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pazienti', '0005_auto_20170301_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='paziente',
            name='modalita_ultima_assunzione',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalità ultima assunzione'),
        ),
    ]
